### PR TITLE
Add modal dialog_was_opened flag

### PR DESCRIPTION
**Pull request by kitchoi**
I needed to test if a dialog is indeed opened in many occasions.   The flag would be a nice thing to have.

@corranwebster flag does solve the problem!
My previous attempt failed because of some stupid mistake which leads to non-modal dialog being opened.

### CODE REVIEW

**Comment by mdickinson** [comment]
@kitchoi: For your particular use case, can you supply a `when_opened` callable that has some side-effect, and then test for that side-effect? Or does that not work?

**Comment by kitchoi** [comment]
@mdickinson A ``when_opened`` function with side-effect does work.
Currently this is what I did to achieve the same effect.   And I have to do this for many tests.

```
tester = ModalDialogTester(the_function_that_should_open_a_dialog)
tester.dialog_was_opened = False

def when_opened(tester):
    tester.dialog_was_opened = True
    tester.close(accept=True)

tester.open_and_run(when_opened=when_opened)
self.assertTrue(tester.dialog_was_opened)
```

**Comment by itziakos** [comment]
Would something like this in the TestCase help you avoid duplication?

```
context = {}
tester.open_and_run(when_opened=self.check_opened, context)
self.assertIn('opened', context)

def check_opened(self, tester, context):
    context['opened'] = True
    tester.close(accept=True)
```

However, the following also fails with a timeout error if a dialog/window was not opened

```
tester.open_and_wait(when_opened=lamda x: x.close(accept=True))
````

**Comment by kitchoi** [comment]
Indeed I did something similar, and is refactored to be used across different test cases.  Just wondered if this is also done across projects then it may be helpful to have it in the modal dialog tester already.

**Comment by mdickinson** [comment]
The change LGTM. I don't think we have any actual reStructuredText docs for the `ModalDialogTester`, but please could you expand the docstring to mention the `dialog_was_opened` attribute?

**Comment by kitchoi** [comment]
I edited the docstring.  Is this good to merge?

**Comment by corranwebster** [comment]
LGTM

**Pull request merged**
