### PR TITLE
Remove usage of logging.warn in favour of logger.warning.

### LINKED ISSUE #165: Use of `logging.warn` in PyFace
PyFace uses `logging.warn` to warn about deprecated bits and pieces.  It should use a `logger.warn` call instead: `logging.warn` has the side-effect of calling `logging.basicConfig`, which means that any subsequent attempts to `logging.basicConfig` in application code silently do nothing.

### PR DESCRIPTION
**Pull request by corranwebster**
Fixes #165 

Global search-and-replace on untested, deprecated code.  Fun, hopefully it works :)

### CODE REVIEW

**Comment by corranwebster** [comment]
@mdickinson Care to review, since you reported #165 ?

**Comment by mdickinson** [comment]
LGTM!  A quick `grin` through the source code doesn't show me any more `logging.*` calls that should be changed, though I do see a good few uses of the root logger that should probably be fixed: i.e., modules with `logger = logging.getLogger()` rather than `logger = logging.getLogger(__name__)` (for example).

**Comment by mdickinson** [comment]
> that should probably be fixed

Not necessarily in this PR, of course.

**Comment by corranwebster** [comment]
Well, actually, now that you mention it, I forgot the `__name__` in my global search-and-replace which removed the `logging.warn`...

**Comment by mdickinson** [comment]
LGTM

**Pull request merged**
