### PR TITLE
Update .travis.yml for Qt

### PR DESCRIPTION
**Pull request by kitchoi**
CI is currently failing with this error:
```
[EXECUTING] /home/travis/.edm/envs/edm/bin/edm run -e pyface-test-3.6-pyside2 -- coverage run -p -m unittest discover -v pyface
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
Command '['/home/travis/.edm/envs/edm/bin/edm', 'run', '-e', 'pyface-test-3.6-pyside2', '--', 'coverage', 'run', '-p', '-m', 'unittest', 'discover', '-v', 'pyface']' returned non-zero exit status 250.
```

This PR attempts to fix this.

### CODE REVIEW

**Comment by mdickinson** [comment]
FWIW, here's fix for this issue that worked for Envisage: https://github.com/enthought/envisage/pull/287

**Comment by kitchoi** [comment]
Yep. Was trying to see whether other alternatives would work as parallel experiments. Enable does this differently too 😂

**Comment by mdickinson** [comment]
> Was trying to see whether other alternatives would work as parallel experiments.

Right, I'm not fond of the Envisage solution, and would be interested in better alternatives.

**Comment by mdickinson** [comment]
It looks as though you're being bitten by this: https://github.com/enthought/buildsystem/issues/3178

**Comment by kitchoi** [comment]
> It looks as though you're being bitten by this: enthought/buildsystem#3178

Looks like updating the OSX image fixed this. The libxml on the default OSX image was too old for the Qt version we are using.
The last commit has built successfully on OSX: https://travis-ci.org/github/enthought/pyface/jobs/695149507

I have been manually terminating other builds not relevant to my testing so I could focus on one thing at a time :)

**Comment by kitchoi** [comment]
> The last commit has built successfully on OSX

Correction: The build actually *failed*, but that failure was caused by an assertion error in test. That is orthogonal to the objective of this draft PR. The entire test suite had been run.

**Comment by kitchoi** [comment]
If it is okay, I would propose doing a squash-and-merge for this PR. Many of the commits are experimental, messy and possibly confusing when read on its own. I hope the comment above will provide the history needed for future references.

**Comment by mdickinson** [comment]
> I would propose doing a squash-and-merge for this PR

:+1:

**Comment by kitchoi** [comment]
Thank you! Squashing and merging...

> It seems possible that the need to specify a particular OS X image could be reverted once the buildsystem issue is solved.

Agreed.

**Pull request merged**
