### PR TITLE
Split task application

### PR DESCRIPTION
**Pull request by corranwebster**
This splits up the `TaskApplication` from @jonathanrocher's #198, breaking out the things that are not Tasks-specific into their own base class that could be used for more basic applications (eg. pure Pyface, TraitsUI or Workbench).

It also cleans up the example somewhat.

### CODE REVIEW

**Comment by corranwebster** [comment]
@jonathanrocher Do these changes seem reasonable to incorporate into your PR?

**Comment by corranwebster** [comment]
Merged master instead of feature/add_tasks_application so histories are now messed up.  May need to cherry-pick into a new branch and try again.

**Comment by jonathanrocher** [comment]
@corranwebster Thanks for contributing to my PR. Traveling in Europe right now, with spotty access to internet. Will try to take a look, but it is hard to disentangle your changes from the merge of master. Which commits would you cherry-pick? I can try to look at them individually if they are not too many.

**Comment by corranwebster** [comment]
No rush on this - I'm teaching in the bay area today, so I'll disentangle it this evening or tomorrow morning, as jetlag allows.

**Comment by jonathanrocher** [comment]
@corranwebster What would you like to do with this PR?

**Comment by corranwebster** [comment]
Closed in favour of #229

**Pull request closed without merging**
