### PR TITLE
Modernise Packaging and CI

### LINKED ISSUE #1107: TaskWindow still visible after shutdown
I'm seeing a situation in which a Pyface `TaskWindow` is still visible even after everything has been closed and shut down. At that point, there seems to be no evidence that the corresponding `QWindow` object still exists in either the Python domain or the C++ domain.

Here's a script to reproduce on my machine:
```python
from pyface.qt import QtCore
from pyface.qt.QtGui import QApplication
from pyface.tasks.api import TaskWindow


def run_event_loop_for_fixed_time(time):
    app = QApplication.instance()

    timeout_timer = QtCore.QTimer()
    timeout_timer.setSingleShot(True)
    timeout_timer.setInterval(round(time * 1000.0))
    timeout_timer.timeout.connect(app.quit)

    timeout_timer.start()
    try:
        app.exec_()
    finally:
        timeout_timer.stop()


def report_window_destroyed(window):
    print("Window destroyed:", window)


def test_lifecycle():

    window = TaskWindow()
    window.open()
    run_event_loop_for_fixed_time(3.0)

    window.control.destroyed.connect(report_window_destroyed)
    window.close()
    run_event_loop_for_fixed_time(3.0)


def main():
    test_lifecycle()
    import gc; gc.collect()
    run_event_loop_for_fixed_time(3.0)

    # The task's QWindow is still visible at this point, but there's no
    # evidence of the application having any QObjects still alive.
    import pdb; pdb.set_trace()


if __name__ == "__main__":
    main()
```

When I run this script, at the point where the script drops into the `pdb` debugger, the window is still visible (but not fully functional: it can't be minimised or closed, for example), but looking at `gc.get_objects()`, I see no evidence of any Python-side `QObjects` still being alive, besides two `QApplication` objects.

Exciting screenshot of a blank window:
Screenshot 2022-02-16 at 14 49 59

### LINKED ISSUE #1194: Should 'import pyface.api' set the toolkit to 'qt' rather than 'qt4'?
Currently, `import pyface.api` in an environment containing PySide or PyQt sets the ETS toolkit to `"qt4"`. This causes issues if an application later tries to set the toolkit to `"qt"`. Would it make more sense for the Pyface import to be setting a toolkit of `"qt"` instead?

Reproducer:
```
mdickinson@mirzakhani Desktop % edm env create --force --version 3.8 testing
Removing environment: testing
Fetching indices for runtime repositories. done
Installing runtime... done
Fetching indices for package repositories. done
Installing/removing package(s)

mdickinson@mirzakhani Desktop % edm install --add-repository enthought/lgpl -e testing pyface pyside6
Fetching indices for package repositories.. done

The following packages will be installed:

    importlib_resources  5.4.0-1      27     KiB
    libfreetype          2.12.1-1    637     KiB
    libharfbuzz          3.2.0-4     924     KiB
    libicu               70.1-2       14.55  MiB
    libpng               1.6.37-100  242     KiB
    libturbojpeg         2.1.2-1     430     KiB
    libzstd              1.5.0-1       1.12  MiB
    pyface               7.4.4-2       2.41  MiB
    pyside6              6.2.3-6      11     MiB
    qtbase               6.2.3-3      11.02  MiB
    qtdeclarative        6.2.3-2       8.92  MiB
    qtmultimedia         6.2.3-3     542     KiB
    qtshadertools        6.2.3-2       1.54  MiB
    qtsvg                6.2.3-2     217     KiB
    qttools              6.2.3-3     468     KiB
    shiboken6            6.2.3-4     259     KiB
    traits               6.4.1-1       4.76  MiB
    zipp                 3.7.0-1       6     KiB

Do you want to continue ? [Y/n]: y
Installing/removing package(s)
pyside6             [............................................................................................]
mdickinson@mirzakhani Desktop % edm run -e testing -- python
Enthought Deployment Manager -- https://www.enthought.com
Python 3.8.12 |Enthought, Inc. (x86_64)| (default, Sep 27 2021, 11:51:02) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyface.api
>>> from traits.etsconfig.api import ETSConfig
>>> ETSConfig.toolkit
'qt4'
```

### LINKED ISSUE #1207: Segfaults on PIL image tests
## Environment

OS: _Mac_
Python version: _3.8_
Toolkit: _Qt_
Qt API: _PySide6_ (may occur on others, not tested)

## Description

I am seeing a test Pyface segfault only on EDM-based MacOS runs of Python 3.8, PySide6 on GitHub; I can’t reproduce locally even when running the same setup.

The failure is happening in a call out to PIL to get the bytes of an image, and is working on all other platforms.  I am wondering if this is an issue with pillow_simd on mac, as it doesn’t happen with a pip-installed pillow.
```test_create_bitmap (pyface.tests.test_pil_image.TestPILImage) ... Fatal Python error: Illegal instruction

Current thread 0x000000010cb94600 (most recent call first):
  File "/Users/runner/work/pyface/pyface/.edm/envs/pyface-test-3.8-pyside6/lib/python3.8/site-packages/PIL/Image.py", line 728 in tobytes
  File "/Users/runner/work/pyface/pyface/.edm/envs/pyface-test-3.8-pyside6/lib/python3.8/site-packages/PIL/ImageQt.py", line 168 in _toqclass_helper
  File "/Users/runner/work/pyface/pyface/.edm/envs/pyface-test-3.8-pyside6/lib/python3.8/site-packages/PIL/ImageQt.py", line 197 in __init__
  File "/Users/runner/work/pyface/pyface/.edm/envs/pyface-test-3.8-pyside6/lib/python3.8/site-packages/pyface/ui/qt4/pil_image.py", line 42 in create_image
  File "/Users/runner/work/pyface/pyface/.edm/envs/pyface-test-3.8-pyside6/lib/python3.8/site-packages/pyface/i_pil_image.py", line 55 in create_bitmap
  File "/Users/runner/work/pyface/pyface/.edm/envs/pyface-test-3.8-pyside6/lib/python3.8/site-packages/pyface/tests/test_pil_image.py", line 53 in test_create_bitmap
 ```

## Steps to Reproduce

Run GitHub CI on Python 3.8/PySide6

### PR DESCRIPTION
**Pull request by corranwebster**
This PR:

- [x] removes setup.py and uses pyproject.toml instead (version information is now only via importlib.metadata)
- [x] runs CI using PyPI and `pip` with Python 3.8 and 3.10 - matrix is Pyside2, PySide6, PyQt5 on all platforms; wxPython on windows only (due to problems installing wheels)
- [x] updates EDM-based ci to use Python 3.8 and PySide6 only
- [x] adds a github action for installing Qt dependencies on ubuntu (copied from TraitsUI)
- [x] switches to using `qt` as the name of the qt toolkit instance instead of `qt4` (but the latter still works, we just prefer `ETS_TOOLKIT=qt` not `ETS_TOOLKIT=qt4`) - fixes #1194 
- [x] fixes #1207
- [x] cleans up the `SplitEditorAreaPane` tests and generally makes Tasks `destroy` methods idempotent, which helps test robustness and fixes #1107 

This will need an update to the expected tests before merging.

### CODE REVIEW

**Review by mdickinson — APPROVED** [review]
LGTM; a couple of nitpick-level comments and suggestions.

**Comment by mdickinson** [comment]
There are a couple of references to `setup.py` turning up in random places. `.gitignore` is one.

**Comment by mdickinson** [comment]
I think we can get rid of `.gitattributes` at this point, too.

**Comment by corranwebster** [comment]
Not specifying all checks to be required for now, but doing a representative cross section - we are likely to end up with a minimal set run in PR checks in the future and then a full matrix across all everything we intend to support run as weekly integration tests.

**Pull request merged**
