### PR TITLE
Release 5.1.0

### PR DESCRIPTION
**Pull request by kitchoi**
- [x] Modify some imports for generating documentation.
- [x] Run tox with Pyside and Python2.7  (Pass)
- [x] Run tox with wxPython (2.8) and Python 2.7  (Pass)
- [x] Run tox with Pyside and Python 3.4 (Pass)
- [ ] Run tox with wxPython and Python 3.4

### CODE REVIEW

**Comment by stefanoborini** [comment]
We found an annoyance and possible source of problems with PySide and OSX. I will open an issue for it.

**Comment by kitchoi** [comment]
@stefanoborini For the record, the problem is regarding running tox tests with PySide on OSX.  So it affects traitsui too, and is orthogonal to the release.  tox tests passed on Linux, and on OSX with a custom build of PySide and Qt libraries.

**Comment by stefanoborini** [comment]
Yes it's generally not a stopper, but it's an annoyance if we want to setup tox to work spot on.

**Comment by kitchoi** [comment]
@corranwebster, @jdmarch  if no more PR to be merged for the release, I will flag IS_RELEASE and make a tag in the next few hours.

**Comment by kitchoi** [comment]
@corranwebster  ready to merge too.

**Comment by kitchoi** [comment]
Appveyor seems to have hung...

**Comment by kitchoi** [comment]
travis tests passed and appveyor branch test passed.  Merging.

**Pull request merged**
