### PR TITLE
Updated Line 34 as per #940

### PR DESCRIPTION
**Pull request by Palash-Vishnani**
Updated deprecated font-related aliases on line 34

### CODE REVIEW

**Comment by corranwebster** [comment]
Thanks for the PR!

I think the point of #940 (although perhaps not clearly expressed) was that these constants need to be updated throughout the codebase (eg. here:
https://github.com/enthought/pyface/blob/004d6ee43acaa51b17e78707f8aeb1118d818725/examples/undo/example_editor_manager.py#L76
and here:
https://github.com/enthought/pyface/blob/004d6ee43acaa51b17e78707f8aeb1118d818725/pyface/wx/scrolled_message_dialog.py#L34
and so on...)

**Comment by Palash-Vishnani** [comment]
@corranwebster @rahulporuri  If you want I can update all such constants through the codebase and then send you a PR, but it will take some time. Until then are you merging this one??

**Comment by corranwebster** [comment]
I'll leave that decision up to @rahulporuri.

**Comment by rahulporuri** [comment]
Thanks for the contribution @Palash-Vishnani ! I'm happy merging this PR as it is. If you can find the time, we'd appreciate any subsequent PRs that will help close #940 .

**Review by rahulporuri — APPROVED** [review]
LGTM

**Pull request merged**
