### PR TITLE
Bug: Readonly CodeEditor allowed adding newlines in view

### PR DESCRIPTION
**Pull request by pankajp**
Fixes https://github.com/enthought/traitsui/issues/264

### CODE REVIEW

**Comment by dpinte** [comment]
@pankajp LGTM. I suppose there are no existing tests we can extend to check this code.

**Comment by pankajp** [comment]
There's test in traitsui for CodeEditor, i could add tests there. But pyface doesn't have anything, and i'm still trying to figure out where do i add a new test.

**Comment by dpinte** [comment]
ideally, we would prefer not having to do two releases for this fix (pyface for the fix and traitsui for the tests) ;-)

**Comment by pankajp** [comment]
Yep, i'm adding a simple test to pyface

**Comment by dpinte** [comment]
thanks!

**Comment by pankajp** [comment]
Added (and fixed) tests.

**Comment by dpinte** [comment]
@corranwebster Could you review?

**Comment by corranwebster** [comment]
LGTM.  Merging.

**Pull request merged**
