### PR TITLE
Install pyside2 using edm instead of pip

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR updates `etstool.py` to install `PySide2` using EDM instead of installing it using pip. This is now possible because `PySide2` v 5.14.1 is available via EDM.

### CODE REVIEW

**Comment by rahulporuri** [comment]
we see a segfault this time - 

```
test_mimeData (pyface.ui.qt4.data_view.tests.test_data_view_item_model.TestDataViewItemModel) ... Fatal Python error: Segmentation fault

Current thread 0x00007f1f34ad9700 (most recent call first):

  File "/home/travis/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/pyface/ui/qt4/data_view/tests/test_data_view_item_model.py", line 61 in test_mimeData
```

note that I am able to reproduce the segfault locally.

**Comment by corranwebster** [comment]
We weren't seeing this segfault under the pip-installed PySide2, right?

I am recalling possibly having seen something like this before where PySide2 returns a different type of "collection of bytes" object that PyQt does - this may be an actual error, although perhaps only one in the test suite.

**Comment by kitchoi** [comment]
> We weren't seeing this segfault under the pip-installed PySide2, right?

I tested master with the pip-installed PySide2 5.14.1 on OSX and could not reproduce the error.

**Comment by corranwebster** [comment]
Yep, I think this is a bug, and it is also present in actual code.  The line just before the crash should read:
```
        raw_data = mime_data.data('text/plain').data()
```
(note the extra `.data()`).  I think a similar change needs to be made in the data wrapper module.

**Comment by corranwebster** [comment]
I have opened #772 to hopefully fix the test failures.

**Comment by kitchoi** [comment]
>> We weren't seeing this segfault under the pip-installed PySide2, right?
>
> I tested master with the pip-installed PySide2 5.14.1 on OSX and could not reproduce the error.

My apologies. Actually, I can reproduce on OSX and PySide2 5.14.1 from PyPI. I think for my previous comment I was running the test suite in an environment installed from PyPI and without NumPy, that particular test case is skipped if NumPy is not available (for it depends on ArrayDataModel, it would be nicer if the test about mime data could be free of NumPy dependency, but that's a separate topic).

To reproduce:
```
$ pip install pyside2==5.14.1 numpy pygments
$ git checkout master
$ pip install .
$ python -m unittest pyface.ui.qt4.data_view.tests.test_data_view_item_model.TestDataViewItemModel.test_mimeData
Segmentation fault: 11
```

**Comment by kitchoi** [comment]
Also, for the record, after upgrading to PySide2 5.15.1, I no longer see the segmentation fault.
```
$ pip install "pyside2>=5.15"
...
Successfully installed pyside2-5.15.1 shiboken2-5.15.1
(pyface-7.1.0-test) kchoi-mbp2019:pyface kchoi$ python -m unittest pyface.ui.qt4.data_view.tests.test_data_view_item_model.TestDataViewItemModel.test_mimeData
/Users/kchoi/Work/ETS/venvs/pyface-7.1.0-test/lib/python3.8/site-packages/traits/traits.py:330: DeprecationWarning: 'TraitMap' trait handler has been deprecated. Use Map instead.
  other.append(TraitMap(map))
.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK 
```
(The deprecation warning there is an open issue on traits)

**Comment by rahulporuri** [comment]
Closing as the experiment revealed missing webkit submodule from our build of PySide2. We will want to try this again when the next update of PySide2 is available via edm.

**Pull request closed without merging**
