### PR TITLE
Deprecate wx toolkit default

### PR DESCRIPTION
**Pull request by corranwebster**
Unfortunately, can't easily test this because `_init_toolkit()` pulls the ladder up after itself, so we can't reset the toolkit to test the code.

### CODE REVIEW

**Comment by corranwebster** [comment]
@itziakos care to do a quick check of this code.

I notice that appveyor seems to be paying attention to this code, but the failure is spurious.

**Comment by itziakos** [comment]
> I notice that appveyor seems to be paying attention to this code, but the failure is spurious.

It was a problem with the appveyor settings, I have updated the configuration to not try to built branches that do not have an appveyor.yml

**Comment by itziakos** [comment]
a tests similar to what was done in https://github.com/enthought/traitsui/pull/229 should be added.

**Comment by corranwebster** [comment]
@itziakos You can't test this in the same way with the code as currently written: once the `toolkit` module is imported for the first time it self-deletes the `_init_toolkit` method we want to test.

You could probably do it with hacky `reload`ing of the module, but I don't want to go there.

**Comment by itziakos** [comment]
> You could probably do it with hacky reloading of the module, but I don't want to go there.

fair enough

**Comment by jwiggins** [comment]
I'm looking forward to the equivalent of nucleic/enaml#165 someday :smile:

**Pull request merged**
