### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by corranwebster**
Update CHANGES.txt and version numbers for 5.0.0 release.

This is not ready for merge yet (release flag is not set).

### CODE REVIEW

**Comment by dpinte** [comment]
@corranwebster LGTM

**Comment by mdickinson** [comment]
Just for information, what's the rationale for the major version number bump?

**Comment by dpinte** [comment]
@mdickinson the change of default from `wx` to `qt`. In the various discussions around it, people seem to think it required a major version change.

**Comment by mdickinson** [comment]
Okay, thanks!

**Comment by corranwebster** [comment]
Looks like there was a failure on appveyor building PySide.  @itziakos any ideas?

**Pull request merged**
