### PR TITLE
Fix task dock pane layout for Qt5.6+

### LINKED ISSUE #442: Dock pane size control fails with Qt5
[This code](https://github.com/enthought/pyface/blob/e047d8b882f2d2f52b4a4a8e7c6af86be2489143/pyface/ui/qt4/tasks/main_window_layout.py#L270-L273) is supposed to allow control of the width and height of the dock panes in a tasks window.

It works as desired with PyQt 4, but apparently no longer works with PyQt 5.

To reproduce:
- build a PyQt 5-based test environment (e.g., with etstool, pyface-test-3.6-pyqt5)
- run `examples/tasks/basic/run.py` in that environment to show one of the example applications
- in `run.py`, add "width=500" to the `PaneItem` in `_default_layout_default`.
- run the application again. Expected behaviour is that the left-hand pane has width 500 pixels. Observed behaviour is that the value of `500` is ignored.

Under PyQt 4, the width is respected.

Digging deeper, PyQt4 uses a rather horrible hack to make this work: it sets both the maximum and minimum size of the dock pane's child using the given layout information (resulting in a fixed size pane), and then after Qt had performed layout, [removes those restrictions](https://github.com/enthought/pyface/blob/e047d8b882f2d2f52b4a4a8e7c6af86be2489143/pyface/ui/qt4/tasks/main_window_layout.py#L282-L295), resetting the max and min sizes of the dock pane and its child.

This hack apparently no longer works on PyQt5.

From reading, the right way to fix this may be to have a custom subclass of `QWidget` that supplies the appropriate size hint on demand.

### PR DESCRIPTION
**Pull request by corranwebster**
This fixes #442 for Qt 5.6+.

Needs testing.

### CODE REVIEW

**Comment by corranwebster** [comment]
@rahulporuri can you check if this resolves #442 for your use case?

**Comment by corranwebster** [comment]
Save and restore is done in Envisage, not here, so it feels like there may be a separate issue around that.

Obvious but should-be-checked question: are you running things with a clear `ETSConfig.application_home` directory.  In the past I have seen issues with restoring state because of runtime difference. Python 2 vs Python 3 was the major one, but changes in the application - eg. changes to class location or definitions - can cause problems with unpickling even when switching branches or environments.

**Comment by rahulporuri** [comment]
I just tested this again - after checking that the app home dir is nuked - and i still see the same issue. The behavior is different from that on master but it doesn't fix the issue of dock panes not getting restored to their previous state.

It's possible that the application i am testing this against is running into an envisage bug.

I don't have a concrete way to reproduce this purely using traitsui/pyface.

**Comment by rahulporuri** [comment]
@kitchoi @corranwebster i think we can close this PR now

**Comment by rahulporuri** [comment]
closing this PR as an alternative fix has been merged in #545

**Pull request closed without merging**
